pipeline {
    agent any

    stages {
        stage ('Execute Unit Tests') {
            parallel {
                stage('Unit Tests - Backend') {
                        agent {
                            docker {
                                image 'snakee/golang-junit:1.21'
                                reuseNode true
                            }
                        }
                        steps {
                            dir('bugtracker-backend') {
                                sh 'go test -v ./...'
                            }
                        }
                    }

                stage ('Unit Tests - Frontend'){
                    agent{
                        docker {
                            imager 'node:20-alpine'
                                reuseNode true
                            }
                        }
                        steps {
                            dir('bugtracker-frontend'){
                                sh '''
                                    npm ci
                                    npm test
                                    mkdir -p reports
                                    mv coverage reports/
                                '''
                            }
                        }
                        post {
                            always {
                                junit 'bugtracker-frontend/test-results.xml'
                                publishHTML target: [
                                    reportDir: 'bugtracker-frontend/reports/coverage',
                                    reportsFiles: 'index.html',
                                    reportName: 'Frontend Coverage Report'
                                ]
                            }
                        }
                    }
            }
        }
    }
}